import type { ClipQueueItem } from '../../main/services/trades/tradeClipPipeline'

export const youtubeStudioUploadUrl = 'https://studio.youtube.com'

const formatDuration = (seconds: number): string => {
  const minutes = Math.floor(seconds / 60)
  const rest = Math.round(seconds % 60)
  return minutes > 0 ? `${minutes}m ${rest}s` : `${rest}s`
}

export const buildManualYouTubeDescription = (clip: ClipQueueItem): string => [
  'Trade clip generated by TradeCut',
  '',
  `Exchange: ${clip.exchange}`,
  `Market: ${clip.marketType}`,
  `Symbol: ${clip.symbol}`,
  `Side: ${clip.side}`,
  `Entry: ${new Date(clip.entryTimeMs).toISOString()}`,
  `Exit: ${new Date(clip.exitTimeMs).toISOString()}`,
  `Duration: ${formatDuration(clip.durationSeconds)}`,
  '',
  'Uploaded manually via YouTube Studio'
].join('\n')
