export type YouTubeTradeMetadata = {
  exchange: string
  marketType: string
  symbol: string
  side: string
  entryTime: string
  exitTime: string
  duration: string
  pnl?: string
  journalUrl?: string
}

export const renderYouTubeTitle = (trade: YouTubeTradeMetadata): string =>
  `${trade.symbol} ${trade.side} trade — ${trade.entryTime} — ${trade.exchange}`

export const renderYouTubeDescription = (trade: YouTubeTradeMetadata): string => {
  const pnl = trade.pnl ?? 'n/a'
  const journalUrl = trade.journalUrl ?? 'n/a'

  return [
    'Trade clip generated by TradeCut',
    '',
    `Exchange: ${trade.exchange}`,
    `Market: ${trade.marketType}`,
    `Symbol: ${trade.symbol}`,
    `Side: ${trade.side}`,
    `Entry: ${trade.entryTime}`,
    `Exit: ${trade.exitTime}`,
    `Duration: ${trade.duration}`,
    `PnL: ${pnl}`,
    '',
    `Journal: ${journalUrl}`
  ].join('\n')
}
