import { describe, expect, it } from 'vitest'
import type { ClipQueueItem } from '../../src/main/services/trades/tradeClipPipeline'
import { buildManualYouTubeDescription, youtubeStudioUploadUrl } from '../../src/renderer/lib/youtubeManualUpload'

const clip: ClipQueueItem = {
  id: 'clip-1',
  status: 'pending-review',
  title: 'BTCUSDT Binance 22.05.26 14:32:11',
  fileName: 'BTCUSDT Binance 22.05.26 14:32:11.mp4',
  videoPath: '/tmp/BTCUSDT Binance 22.05.26 14:32:11.mp4',
  metadataPath: '/tmp/BTCUSDT Binance 22.05.26 14:32:11.json',
  symbol: 'BTCUSDT',
  side: 'LONG',
  exchange: 'Binance',
  marketType: 'Futures',
  entryTimeMs: Date.UTC(2026, 4, 22, 11, 31, 0),
  exitTimeMs: Date.UTC(2026, 4, 22, 11, 32, 11),
  durationSeconds: 71,
  createdAtMs: Date.UTC(2026, 4, 22, 11, 32, 12)
}

describe('manual YouTube upload helpers', () => {
  it('points manual publishing at YouTube Studio', () => {
    expect(youtubeStudioUploadUrl).toBe('https://studio.youtube.com')
  })

  it('builds a copyable description from queue clip metadata', () => {
    const description = buildManualYouTubeDescription(clip)

    expect(description).toContain('Trade clip generated by TradeCut')
    expect(description).toContain('Exchange: Binance')
    expect(description).toContain('Market: Futures')
    expect(description).toContain('Symbol: BTCUSDT')
    expect(description).toContain('Side: LONG')
    expect(description).toContain('Duration: 1m 11s')
  })
})
